export const DEFAULT_DATE_FORMAT_TOKEN = "yyyy-MM-dd"
export const DEFAULT_TIME_FORMAT_TOKEN = "HH:mm:ss"
export const DEFAULT_DATETIME_FORMAT_TOKEN = `${DEFAULT_DATE_FORMAT_TOKEN} ${DEFAULT_TIME_FORMAT_TOKEN}`
