# This is a basic workflow to help you get started with Actions

name: Deploy StoryBook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # yarn install
    - name: Install
      run: yarn install

    # build typescript
    - name: Build
      run: yarn build:storybook
   
    # Deployment
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v2.0.3
      with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID}}  #Required
          now-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./storybook-static
