name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - 'sb*'

jobs:
  deploy_storybook:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Cache NPM dependencies
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-cache-

    # yarn install
    - name: Install
      run: yarn install

    # build storybook
    - name: Build
      run: yarn build:storybook

    # Deployment
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v2.0.3
      with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID}}  #Required
          now-project-id: ${{ secrets.PROJECT_ID}} #Required
          now-args: '--prod' #Optional
          working-directory: ./storybook-static
